title: "How&Best"
email: gmail@gmail.com
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: zh_TW
lang: zh_TW
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-23PHVYR1V0

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/sal.png'
    email: 1@gmail.com
    web: https://howandbest.github.io/
    twitter: https://howandbest.github.io/
    description: "This is the author box."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: 2@gmail.com
    web: https://howandbest.github.io/
    twitter: https://howandbest.github.io/
    description: "This is the author box."

# Social
social:
  instagram: https://howandbest.github.io/
  facebook: https://howandbest.github.io/
  twitter: https://howandbest.github.io/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives